"""The standard Google-dork query generator and section orchestration.

:func:`build_queries` produces a scored set of standard dork variations for one
mode. :func:`build_sections` assembles the full UI output: the Quick/Deep/God
tiers plus an optional, clearly-separated Open Directory section.

Open-directory queries are generated by :mod:`src.core.opendir`; they are kept
in their own section so their specialised syntax never dilutes the standard
tiers (and vice versa).
"""

from __future__ import annotations

from dataclasses import replace

from src.config import ARCHIVE_SITES, MODES, OBJECTIVES, PASTE_SITES
from src.core import _format as fmt
from src.core.models import DorkRequest, QueryResult, QueryVariation, Section
from src.core.opendir import build_opendir_queries

# Objective-specific hint tokens layered on top of the user's keywords.
_OBJECTIVE_TERMS: dict[str, dict[str, list[str]]] = {
    "documents": {"intitle": ["report", "documentation"]},
    "books": {"intitle": ["book", "ebook"]},
    "panels": {
        "intitle": ["admin", "login", "dashboard"],
        "inurl": ["admin", "login", "portal"],
    },
    "directories": {"intitle": ["index of"], "intext": ["parent directory"]},
}


def build_queries(req: DorkRequest) -> QueryResult:
    """Build a scored set of standard dork variations for ``req``'s mode.

    The most powerful (highest scoring) variation is marked as recommended.
    Open-directory generation is intentionally *not* triggered here — callers
    use :func:`build_opendir_queries` for that so the two stay separate.
    """
    mode = MODES.get(req.mode, MODES["quick"])
    objective = OBJECTIVES.get(req.objective, OBJECTIVES["documents"])
    hints = _OBJECTIVE_TERMS.get(req.objective, {})

    includes = fmt.keywords_fragment(req.include_keywords)
    excludes = fmt.excludes_fragment(req.exclude_keywords)
    site = fmt.site_fragment(req.site)
    filetypes = fmt.filetype_or(req.filetypes)

    variations: list[QueryVariation] = []

    # --- Variation 1: the bare-bones baseline (always present) ------------- #
    base_parts = [includes, site, filetypes, excludes]
    variations.append(
        QueryVariation(
            query=fmt.join(base_parts) or includes or "*",
            rationale="Baseline query — broad keyword + core filters.",
            power=1 + bool(site) + bool(filetypes),
        )
    )

    # --- Variation 2: objective-targeted intitle/inurl --------------------- #
    intitle_hint = hints.get("intitle", [])
    inurl_hint = hints.get("inurl", [])
    targeted_parts = list(base_parts)
    if intitle_hint:
        targeted_parts.insert(1, f"intitle:{fmt.quote(intitle_hint[0])}")
    if inurl_hint:
        targeted_parts.insert(2, f"inurl:{inurl_hint[0]}")
    targeted_query = fmt.join(targeted_parts)
    if targeted_query and targeted_query != variations[0].query:
        variations.append(
            QueryVariation(
                query=targeted_query,
                rationale=f"Targeted for '{objective.label}' via intitle/inurl hints.",
                power=3 + bool(site) + bool(filetypes),
            )
        )

    # --- Variation 3: title-locked exact phrase --------------------------- #
    if includes:
        first_kw = req.include_keywords[0]
        title_parts = [f"intitle:{fmt.quote(first_kw)}", site, filetypes, excludes]
        variations.append(
            QueryVariation(
                query=fmt.join(title_parts),
                rationale="Locks your primary keyword into the page title.",
                power=2 + bool(site) + bool(filetypes),
            )
        )

    # Quick Scan stops here — keep it lean.
    if not mode.aggressive and mode.key == "quick":
        return fmt.finalise(variations, mode.max_variations)

    # --- Variation 4: body-text emphasis (Deep+) -------------------------- #
    if includes:
        intext = " ".join(f"intext:{fmt.quote(k)}" for k in req.include_keywords if k.strip())
        deep_parts = [intext, site, filetypes, excludes]
        if intitle_hint:
            deep_parts.insert(0, f"intitle:{fmt.quote(intitle_hint[0])}")
        variations.append(
            QueryVariation(
                query=fmt.join(deep_parts),
                rationale="Forces keywords into page body text for precision.",
                power=4 + bool(site) + bool(filetypes),
            )
        )

    # --- Variation 5/6: aggressive stacked combo (Dork God) --------------- #
    if mode.aggressive:
        agg_parts: list[str] = []
        if intitle_hint:
            agg_parts.append(f"intitle:{fmt.quote(intitle_hint[0])}")
        if inurl_hint:
            agg_parts.append("inurl:(" + "|".join(inurl_hint) + ")")
        agg_parts.append(includes)
        if req.include_keywords:
            agg_parts.append(
                " ".join(f"intext:{fmt.quote(k)}" for k in req.include_keywords if k.strip())
            )
        agg_parts.extend([site, filetypes, excludes])
        variations.append(
            QueryVariation(
                query=fmt.join(agg_parts),
                rationale="Maximum-pressure stack: title + url + body + filters.",
                power=6 + bool(site) + bool(filetypes),
            )
        )

        # A sensitive-exposure flavour for panels/directories objectives.
        if req.objective in {"panels", "directories"}:
            exposure_parts = [
                'intitle:"index of"' if req.objective == "directories" else "inurl:admin",
                includes,
                site,
                filetypes,
                '-intext:"login"' if req.objective == "directories" else "",
                excludes,
            ]
            variations.append(
                QueryVariation(
                    query=fmt.join(exposure_parts),
                    rationale="Exposure-hunting variant tuned to your objective.",
                    power=5 + bool(site) + bool(filetypes),
                )
            )

        # Deep / low-visibility surfacing: recover content that mainstream
        # results miss by pivoting into web archives and public paste dumps.
        variations.extend(_deep_surface_variations(includes, excludes))

    return fmt.finalise(variations, mode.max_variations)


def _deep_surface_variations(includes: str, excludes: str) -> list[QueryVariation]:
    """Build Dork God pivots toward archived / barely-surfaced content.

    Truly un-indexed pages cannot be returned by a search engine, but pages that
    were taken down, rewritten, mirrored, or buried often survive in web
    archives, caches and paste sites. These variations chase those copies — most
    effective when the user supplies a unique identifier (a license plate, a
    handle, a phone number, a wallet address, an exact phrase).
    """
    if not includes:
        return []

    archive_filter = " OR ".join(f"site:{s}" for s in ARCHIVE_SITES)
    paste_filter = " OR ".join(f"site:{s}" for s in PASTE_SITES)

    # Archives & paste sites store HTML snapshots, not typed files — applying a
    # ``filetype:`` filter here returns nothing, so it is deliberately omitted.
    return [
        QueryVariation(
            query=fmt.join([includes, f"({archive_filter})", excludes]),
            rationale="Archived/cached copies — finds pages that were removed or altered.",
            power=7,
        ),
        QueryVariation(
            query=fmt.join([includes, f"({paste_filter})", excludes]),
            rationale="Paste & text-dump sites where unlisted/leaked content first appears.",
            power=7,
        ),
    ]


def build_sections(req: DorkRequest) -> list[Section]:
    """Assemble the full UI output for ``req``.

    Always yields the three standard tiers (Quick Scan, Deep Dork, Dork God).
    When ``req.opendir`` is set, a dedicated Open Directory section is appended
    so its specialised ``index of`` syntax stays separate and accurate rather
    than being mixed into the standard tiers.
    """
    sections: list[Section] = []
    for key, mode in MODES.items():
        result = build_queries(replace(req, mode=key))
        sections.append(Section(key, mode.label, mode.description, result))

    if req.opendir:
        # ewasion/opendirectory-finder logic, reproduced verbatim.
        opendir_result = build_opendir_queries(replace(req, mode="god"))
        sections.append(
            Section(
                key="opendir",
                title="🗂️ Open Directory",
                description="100% ewasion/opendirectory-finder logic · index.of + noise/fake-index filters",
                result=opendir_result,
            )
        )

    return sections


def pick_overall(sections: list[Section]) -> tuple[Section | None, QueryVariation | None]:
    """Return the (section, variation) to headline as the overall recommendation.

    When the user opted into Open Directory hunting, that section's noise-filtered
    powerhouse query is exactly what they came for — so it is surfaced as the
    headline regardless of raw power scores. Otherwise the highest-power
    recommended variation across all standard tiers wins.
    """
    for section in sections:
        if section.key == "opendir" and section.result.recommended is not None:
            return section, section.result.recommended

    best_section: Section | None = None
    best_variation: QueryVariation | None = None
    best_power = -1
    for section in sections:
        recommended = section.result.recommended
        if recommended is not None and recommended.power > best_power:
            best_power = recommended.power
            best_section = section
            best_variation = recommended
    return best_section, best_variation
